### ISSUE TITLE
Dos2unix no such file error on latest

### ISSUE THREAD

**Issue by dooniem** [binhex/arch-qbittorrentvpn#337]
I believe I have the latest image:
 BASE_RELEASE_TAG=2025071102,INT
Now my container won't start, log says:
/usr/sbin/init.sh: line 295: /usr/local/bin/dos2unix.sh: No such file or directory

Am I to change something or did the latest update break something?

**Comment by plexecutor** [comment]
Same here. 

```
___.   .__       .__
\_ |__ |__| ____ |  |__   ____ ___  ___
 | __ \|  |/    \|  |  \_/ __ \\  \/  /
 | \_\ \  |   |  \   Y  \  ___/ >    <
 |___  /__|___|  /___|  /\___  >__/\_ \
     \/        \/     \/     \/      \/
   https://hub.docker.com/u/binhex/

2025-07-14 07:31:33.530047 [info] Host is running unRAID
2025-07-14 07:31:33.566714 [info] System information: Linux 935ac03cd2d2 6.12.24-Unraid #1 SMP PREEMPT_DYNAMIC Sat May  3 00:12:52 PDT 2025 x86_64 GNU/Linux
2025-07-14 07:31:33.602455 [info] Image tags: BASE_RELEASE_TAG=2025071102,INT_RELEASE_TAG=2025071102,IMAGE_RELEASE_TAG=5.1.2-1-04
2025-07-14 07:31:33.643612 [info] PUID defined as '99'
2025-07-14 07:31:33.686428 [info] PGID defined as '100'
2025-07-14 07:31:33.750396 [info] UMASK defined as '000'
2025-07-14 07:31:33.790078 [info] Permissions already set for '/config'
2025-07-14 07:31:33.833240 [info] Deleting files in /tmp (non recursive)...
2025-07-14 07:31:33.885322 [info] VPN_ENABLED defined as 'yes'
2025-07-14 07:31:33.930187 [info] VPN_CLIENT defined as 'wireguard'
2025-07-14 07:31:33.972088 [info] VPN_PROV defined as 'protonvpn'
2025-07-14 07:31:34.032308 [info] WireGuard config file (conf extension) is located at /config/wireguard/wg0.conf
/usr/sbin/init.sh: line 212: /usr/local/bin/dos2unix.sh: No such file or directory

** Press ANY KEY to close this window ** 
```

**Comment by the-fifth** [comment]
You can roll back to a working image by specifying the tag: 5.1.2-1-03 to get your container/stack back up and running.

`image: binhex/arch-qbittorrentvpn:5.1.2-1-03`

**Comment by binhex** [comment]
fixed please pull down latest.

**Comment by halsafar** [comment]
Still getting this on versions 5.1.2-1-04 and 5.1.2-1-05.  The last version that works for me is 5.1.2-1-03.

**Comment by halsafar** [comment]
My bad. I had a custom `entrypoint:` defined in my compose file (to inject a docker secret).  It was still pointing to the old init.sh.
